version: '2'
services:
  node:
    container_name: nodejs
    build: .
    ports:
      - "8080:3000"
    # mapeo archivo de ejecucion
    volumes:
      - "./configs/node/server.js:/usr/src/app/server.js"
  db_server:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=devops_app #creará una base de datos con ese nombre
      - MYSQL_ROOT_PASSWORD=root #clave de administrador del servidor MySQL
    ports:
      - "4400:3306"
    volumes:
      - /var/db/mysql:/var/lib/mysql
      - "./configs/mysql/script.sql:/tmp/script.sql"      
      - "./configs/mysql/exec-script.sh:/tmp/exec-script.sh"